### ISSUE TITLE
No Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by jmulhern** [slok/brigadeterm#22]
Built the binary locally from master today and when trying to run with my google cloud cluster it's giving me the following error. 

```
$ TERM=xterm brigadeterm
No Auth Provider found for name "gcp"
```

**Comment by slok** [comment]
Hi!

Thanks for submitting the issue. This is because brigadeterm only loads the OIDC auth type. I'll add all the available kinds! (Including GCP, Azure...)
