### ISSUE TITLE
Phantom jobs

### ISSUE THREAD

**Issue by FPerezP** [slok/brigadeterm#38]
Hi @slok! First of all, thanks a lot for making this tool a reality! Love it!
This is not a bug per se I'd say, but a weird behaviour related to Brigade phantom jobs. 

**Version**: 0.4.1

**Context**: We have a couple of phantom jobs due to a migration we are doing, so we currently have our brigade.js broken for that branch.

**Issue**
Having these hanging jobs, makes `brigadeterm` behaves a bit weird when listing all available jobs. The phantom ones are randomely sorted, so having the auto refresh feature enabled, makes the list to be changing, and consequently the main project list where we can see an overview of the latest job statuses.

Here a couple of screenshots:

_Project details screen:_
![screenshot from 2018-06-07 12-51-08](https://user-images.githubusercontent.com/479485/41095893-3fed0df0-6a53-11e8-9080-da153f43952c.png)

![screenshot from 2018-06-07 12-51-23](https://user-images.githubusercontent.com/479485/41095905-46bc03e8-6a53-11e8-9457-38ca944976ed.png)

_Projects overview:_
![screenshot from 2018-06-07 13-04-55](https://user-images.githubusercontent.com/479485/41095995-75512526-6a53-11e8-992d-c2a65c63dfe4.png)

![screenshot from 2018-06-07 13-05-02](https://user-images.githubusercontent.com/479485/41095996-7576ac10-6a53-11e8-8cd7-5722251b63af.png)

**Comment by slok** [comment]
Yes, I would say that makes it unusable with the new autoreload feature so it's a *enbugment* :laughing: This issue has high priority, I'll release a minor when fixed.

You can disable autoreload by using `--reload-interval=0s` flag or use [v0.4.0](https://github.com/slok/brigadeterm/releases/tag/v0.4.0) that doesn't have autoreload.

Thanks for reporting it!
