### ISSUE TITLE
Failing stages are not reflected at build level

### ISSUE THREAD

**Issue by FPerezP** [slok/brigadeterm#39]
Hey guys, I'm having another weird issue. I guess this is related to Brigade and not `brigadeterm` specific, but just in case we can do something checking a different parameter or so.

**Version**: 0.4.1
**Issue**: 
Having a job with tests are failing, checking the builds list says that job succeed, but looking into its details we can see that its tests are failing and the job is labeled as failed.

_Jobs overview_
![screenshot from 2018-06-07 13-37-29](https://user-images.githubusercontent.com/479485/41097391-09bd849e-6a58-11e8-9364-95e983d482fc.png)

_Job details_
![screenshot from 2018-06-07 13-37-47](https://user-images.githubusercontent.com/479485/41097392-09f0cbc4-6a58-11e8-9287-bd7d19c12ae8.png)

**Comment by slok** [comment]
This could be a problem of how the pipeline is structured and executed, so the problem would arise on other visualization tools like [kashti](https://github.com/Azure/kashti). I'll keep it open to track it down.

Thanks

**Comment by slok** [comment]
Closing this issue due to be pipeline related and not brigadeterm itself.
