### ISSUE TITLE
Error when starting brigadeterm

### ISSUE THREAD

**Issue by SandeepVaman** [slok/brigadeterm#48]
When I start brigadeterm, sometimes I see below error repeatedly logging in the terminal. I dont face this issue often, but sometimes for a few minutes. 

`ERROR: logging before flag.Parse: E0919 16:18:11.366720    1057 reflector.go:205] github.com/slok/brigadeterm/vendor/github.com/Azure/brigade/pkg/storage/kube/apicache/liststore.go:36: Failed to list *v1.Secret: Unauthorized`

**Comment by slok** [comment]
Hi! That's Kubectl connection error, maybe your token has expired or similar, depends on how you authenticate with your own cluster. It's not something related with brigade or brigadeterm.

Closing.
