### ISSUE TITLE
proposal: default Brigade namespace from environment variable

### ISSUE THREAD

**Issue by radu-matei** [slok/brigadeterm#54]
https://github.com/Azure/brigade/issues/741 proposed (and https://github.com/Azure/brigade/pull/742 implemented) having a default Brigade namespace for the use case when Brigade is deployed in a different namespace, and `--namespace <brigade-namespace>` needs to be passed with each request.

The default namespace is read from the `$BRIGADE_NAMESPACE` environment variable, and if passed, the `--namespace` flag takes precedence.

The same applies for `brigadeterm` as well, so if we think it's a good idea I can also add it here (one I get passed #53).

Thoughts?

**Comment by slok** [comment]
I see a very good feature, It's a very minimal change It takes a minute so not no problem to do it myself at this moment, I'll submit the PR right now :) thanks!

**Comment by slok** [comment]
I just released a [v0.9.1](https://github.com/slok/brigadeterm/releases/tag/v0.9.1) with this change

**Comment by radu-matei** [comment]
Wow, that was impressively fast!
Thanks a lot!
